<div>
	<div class="tab_header">
		<h2 class="tab_title">Search:</h2>
	</div>
	<input type="text" name="searchTerm" class="big_search_box" id="search_box" value="Enter an artist/album/track..."/>
	</br><em>Enter an artist, album or track name above you should see results as your typing. Due to current limitations search terms must be exact. If you cannot find the artist you are looking for you can use our automated process to add new artists; hit request on the left tab to get started. Bugs? email <a href="mailto:support@zcd.me">support@zcd.me</a></em>
</div>
<div id="search_result_holder"></div>