<h1>LIBRARY</h1>
	<a href="#myMusic" id="my_music_button"><h2>My Library</h2></a>
<h1>WAREHOUSE</h1>
	<!--<a href="#browse" id="browse_button"><h2>Browse</h2></a>-->
	<a href="#showSearch" id="search_button"><h2>Search</h2></a>
	<a href="#showRequest" id="request_artist_button"><h2>Request an artist</h2></a>
<h1>PLAYLISTS</h1>
	<a href="#playQueue" id="recently_viewed_button"><h2>Play Queue</h2></a>
<h1>META</h1>
	<a href="#login" id="login_button"><h2>Login</h2></a>
<div id="left_side_bottom_buttons" style="z-index: 1000; background-color: #E9E9F0;">
	<div id='bottom_right_border_fix'></div>
	<p id="youtube_now_playing_text" style="padding: 0px; margin: 0px; font-size: 8px;font-weight: normal; overflow: hidden;width: 200px; float: left; padding-top: 4px;padding-left: 10px;">Content powered by Youtube</p>
	<div class="pointer expand_down" id="show_youtube_button"></div>
	<div id="footer_links_holder">
		 &copy; 2011 <a href="http://mikehershey.com">Mike Hershey</a> | <a href="http://www.zcdmedia.com">ZCD Media</a> | <a href="#contact">Contact</a> | <a href="#legal">Legal</a> | <a href="#privacy">Privacy Policy</a>
	</div>
</div>
<div id='youtube_object_wrapper' style="position: absolute;">
	<div class="tab_header" style="width: 200px; height: 30px; padding: 0px;">
		<p id="youtube_now_playing_text" style="padding: 0px; margin: 0px; font-size: 14px;font-weight: normal; overflow: hidden;float: left;padding-top: 5px;">How's the quality?</p>
		<div id="voting_holder" style="float: right; padding-top: 3px;height: 27px; overflow: hidden;">
			<img src="/images/voting/thumbs-down.png" id="vote_bad_youtube_quality"/>
			<img src="/images/voting/thumbs-up.png" id="vote_good_youtube_quality"/>
		</div>
	</div>
	<div id="videoDiv"></div>
</div>