<!-- minified javascripts are not used, google closure compiler creates consolidated minified js for production builds -->
<link rel="stylesheet" type="text/css" href="/jquery/jquery-ui-1.8.13.custom.css" />
<link rel="stylesheet" type="text/css" href="/styles/main.css" />
<link rel="stylesheet" type="text/css" href="/tablesorter/style.css" />
<link rel="stylesheet" type="text/css" href="/jquery.loading/jquery.loading.1.6.css" />
<link rel="stylesheet" type="text/css" href="/jquery.chosen/chosen.css" />
<link rel="stylesheet" type="text/css" href="/jquery.contextmenu/ContextMenu.css" />
<script type='text/javascript' src='/jquery/jquery-1.7.1.min.js'></script>
<script type='text/javascript' src='/jquery/jquery-ui-1.8.13.custom.min.js'></script>
<script type='text/javascript' src='http://www.youtube.com/player_api'></script>
<script type='text/javascript' src='/javascripts/main.js'></script>
<script type='text/javascript' src='/tablesorter/jquery.tablesorter.js'></script>
<script type='text/javascript' src='/jquery.loading/jquery.loading.1.6.4.min.js'></script>
<script type='text/javascript' src='/javascripts/RequestTab.js'></script>
<script type='text/javascript' src='/javascripts/LogTab.js'></script>
<script type='text/javascript' src='/javascripts/MessageManager.js'></script>
<script type='text/javascript' src='/javascripts/ContactTab.js'></script>
<script type='text/javascript' src='/javascripts/showArtistTab.js'></script>
<script type='text/javascript' src='/javascripts/Sources.js'></script>
<script type='text/javascript' src='/jquery.chosen/chosen.jquery.min.js'></script>
<script type='text/javascript' src='/jquery.contextmenu/ContextMenu.js'></script>