<div id="appheader" class="appheader">
	<h3 class="title">ZCD<br/>Music</h3>
	<div class="music_navigation">
		<a href="#" id="back_button" class="backward_button_position backward_button"></a>
		<a href="#" id="play_pause_button" class="play_pause_button_position play_button"></a>
		<a href="#" id="forward_button" class="forward_button_position forward_button"></a>
	</div>
	<div id="now_playing" class="now_playing">
		<p id="now_playing_artist" class="now_playing_artist">Artist</p>
		<p id="now_playing_track" class="now_playing_track">Track</p>
		<div id="slider-range-min"></div>
	</div>
</div>