<h1>LIBRARY</h1>
	<a href="#myMusic" id="my_music_button"><h2>My Music</h2></a>
<h1>WAREHOUSE</h1>
	<a href="#browse" id="browse_button"><h2>Browse</h2></a>
	<a href="#showSearch" id="search_button"><h2>Search</h2></a>
	<a href="#showRequest" id="request_artist_button"><h2>Request an artist</h2></a>
<h1>PLAYLISTS</h1>
	<a href="#recentlyViewed" id="recently_viewed_button"><h2>Recently Viewed</h2></a>
<h1>META</h1>
	<a href="#login" id="login_button"><h2>Login</h2></a>
	<a href="#" id="contact_button"><h2>Contact</h2></a>
	<a href="#" id="legal_button"><h2>Legal/DMCA</h2></a>
	<a href="#" id="legal_button"><h2>Credits</h2></a>