<h1>LIBRARY</h1>
	<a href="#myMusic" id="my_music_button"><h2>My Library</h2></a>
<h1>WAREHOUSE</h1>
	<a href="#browse" id="browse_button"><h2>Browse</h2></a>
	<a href="#showSearch" id="search_button"><h2>Search</h2></a>
	<a href="#showRequest" id="request_artist_button"><h2>Request an artist</h2></a>
<h1>PLAYLISTS</h1>
	<a href="#playQueue" id="recently_viewed_button"><h2>Play Queue</h2></a>
<h1>META</h1>
	<a href="#login" id="login_button"><h2>Login</h2></a>
	<a href="#" id="contact_button"><h2>Contact</h2></a>
	<a href="#legal" id="legal_button"><h2>Legal/DMCA</h2></a>
	<a href="#" id="credits_button"><h2>Credits</h2></a>
<div id="left_side_bottom_buttons" style="z-index: 1000; background-color: #E9E9F0;">
	<hr/ style="padding: 0; margin: 0;">
	<p id="youtube_now_playing_text" style="padding: 0px; margin: 0px; font-size: 8px;font-weight: normal; overflow: hidden;width: 200px; float: left; padding-top: 4px;padding-left: 10px;">Content powered by Youtube</p>
	<div class="pointer expand_down" id="show_youtube_button"></div>
</div>
<div id="videoDiv" style="display: none;">Loading...</div>