<div id="areYouSureYouHateKittens" title="Are you sure you hate kittens?" style="display: none">
	<p>Our pet kitten Toby hates mean lawyers and gets really depressed when they 
	are around our site. She has been known to hurt herself when depressed. Are 
	you really sure you want to continue?
	</p>
</div>
<div id="thankYouForBeingALawyer" title="Thank you" style="display: none">
	<p>Sorry about that, we just had to verify that you are a lawyer. 
	Based on your answers to the previous question this is now obvious.</p>
</div>