<link rel="stylesheet" type="text/css" href="/jquery/jquery-ui-1.8.13.custom.css" />
<link rel="stylesheet" type="text/css" href="/styles/main.css" />
<link rel="stylesheet" type="text/css" href="/tablesorter/style.css" />
<link rel="stylesheet" type="text/css" href="/jquery.loading/jquery.loading.1.6.css" />
<script type='text/javascript' src='/jquery/jquery-1.5.1.min.js'></script>
<script type='text/javascript' src='/jquery/jquery-ui-1.8.13.custom.min.js'></script>
<script type='text/javascript' src='/javascripts/main.js'></script>
<script type='text/javascript' src='/tablesorter/jquery.tablesorter.min.js'></script>
<script type='text/javascript' src='/jquery.loading/jquery.loading.1.6.4.min.js'></script>
<script type='text/javascript' src='/javascripts/RequestTab.js'></script>
<script type='text/javascript' src='/javascripts/LogTab.js'></script>
<script type='text/javascript' src='/javascripts/MessageManager.js'></script>
