<div>
	<div class="tab_header">
		<h2 class="tab_title">Request > Add an Artist:</h2>
	</div>
	<div class="tab_other_content_block" style="margin: 30px;">
		<h3>Add an artist</h3>
		<form id="request_form" action="#">
			<input type="text" name="artistName" class="big_search_box" id="request_box" value="Enter an artist"/>
			<input type="submit" name="submit" value="submit"/>
		</form>
		<p>This wizard will guide you through the process of adding a new artist to 
		our music database. The system is automated and gathers data from MusicBrainz. 
		To get started please enter the exact name of the artist you wish to add.</p>
		<p>If you have any questions, need help, want to suggest a new feature, or report a bug please 
		don't hesitate to email us at <a href="mailto:support@zcd.me">support@zcd.me</a></p>
	</div>
</div>
