<div id="request_thanks" style="display:none" title="Thanks, we got it">
	<p>The monkeys are dispatched and your music should be loaded in the next 5 minutes or so. We'll try to let you know when its done loading.</p>
</div>
<div>
	<div class="tab_header">
		<h2 class="tab_title">Request:</h2>
	</div>
	<form id="request_form" action="#">
		<input type="text" name="artistName" class="big_search_box" id="request_box" value="Enter an artist" style="width:80%"/><input type="submit" name="submit" class="submit_search" value="submit"/>
	</form>
	<em>Enter an artist and hit submit. Upon submission we will dispatch a team of music loving monkeys to find and save all music recorded by your artist.</em><br/><br/> 
	<em>Note: it may take up to five minutes for new music to be added, meanwhile feel free to browse around or do whatever. We'll do our best to let you know when its been added, but no gaurentees.</em>
</div>
<div id="search_result_holder"></div>	
