<!DOCTYPE HTML>
<html>
	<head>
		<title>Music by ZCD Media</title>

		<link rel="stylesheet" type="text/css" href="/styles/iPhone.css" />

		<!--analytics-->
		<script type="text/javascript">
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-9659788-8']);
			_gaq.push(['_setDomainName', '.zcd.me']);
			_gaq.push(['_trackPageview']);

			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();
		</script>

	</head>
	<body>
		<div id="header">
			<img src="images/ZCDMusicZebra.png" style="width: 80%;" class="center"/>
		</div>
		<div id="buttons">
			<a href="$loginLink$" class="iphone_style_button">Login</a>
			<a href="$loginLink$" class="iphone_style_button">Proceed as guest</a>
		</div>
	</body>
</html>