<div id="logged_in_splash_page" class="tab_other_content_block" style="margin: 30px;">
	<h3>You don't have any songs in your library</h3>
	<p>Music by ZCD Media allows you to create a free online library that you 
	can access from any computer with internet. There's nothing to download 
	and everything is free. Get started by hitting the browse or search 
	buttons on the left side bar. From there you can find music you like and add it to library. 
	</p>
	<p>Note: Database was refreshed on December 11th; all user libraries and the music database have been purged. A batch import of the entire musicbrainz database is underway. This was needed to fix various bugs, mostly character encoding issues.</p>
	<p>If you have any questions, need help, want to suggest a new feature, or report a bug please 
	don't hesitate to email us at <a href="mailto:support@zcd.me">support@zcd.me</a></p>
</div>

<!--<div class="tab_other_content_block center">
	<div id="splash_music_by_zcd_holder" style="height:150px;background-color: #E9E9F0; margin-left: auto; margin-right: auto;">
		<h1 id="splash_music_header_one" style="position: absolute;font-size: 72px;">Music</h1>
		<h2 id="splash_music_header_two" style="position: absolute;font-size: 18px;">by ZCD Media</h2>
		<h3 id="splash_music_slogan" style="text-align: center;font-size: 14px; padding-top: 128px;font-weight: normal">Free music, pure and simple; just like our name.</h3>
	</div>
	<div class="splash_item">
		<div class="album_image_holder">
			<img src="/images/splash/money_128.png" />
		</div>
		<div class="splash_info_holder">
			<h1>100% Free</h1>
			<h2>No play limits. No monthy fees. No audio ads. Ever. You can even opt out of all advertising.</h2>
		</div>
	</div>
	<div class="splash_item">
		<div class="album_image_holder">
			<img src="/images/splash/speaker.png" />
		</div>
		<div class="splash_info_holder">
			<h1>Lots of Music</h1>
			<h2>If we don't already have it you can add or request it.</h2>
		</div>
	</div>
	<div class="splash_item">
		<div class="album_image_holder">
			<img src="/images/splash/github-icon.png" />
		</div>
		<div class="splash_info_holder">
			<h1>Open Source</h1>
			<h2>This entire site is open source (and on Github). <a href="https://github.com/mikehershey/ZCDMusic">Check it out</a>.</h2>
		</div>
	</div>
</div>-->