<div class="tab_header">
	<h2 class="tab_title">Login:</h2>
</div>
<div class="tab_other_content_block" >
	<h3>Login with your Google account</h3>
	<p>You can login with your Google account. The button below will take you to Google's secure login where you can login.<p>
	<a href="$loginLink$" style="cursor: pointer">
		<img src="/images/GoogleSignin.png" style="display: block; margin-left: auto; margin-right: auto"/>
	</a>
</div>