<div id="browse_all_music">
	<div class="tab_header">
		<h2 class="tab_title">Legal:</h2>
	</div>
	<div class="tab_other_content_block" style="padding: 30px;">
		<h3>Please read about how this site works!</h3>
		<p>Music by ZCD Media does not store any music in our servers. All of our 
		on demand music is powered by Youtube. We do not have the power to remove 
		youtube videos from their site, as a convenience here is their DMCA takedown link: 
		<a href="http://www.youtube.com/t/dmca_policy">http://www.youtube.com/t/dmca_policy</a>. 
		
		<p>Again let me reiterate we do not actually play any music for users, our entire site 
		is a huge lie, all we do is aggregate Youtube links. If you email me with enough lawyery 
		sounding terms you can probably scare me into removing youtube links from the site.</p>
		
		<p>We do (or will in the future) allow users to upload some content such as images, to describe 
		albums and artists and disambiguate them from similar artists and albums as well as to 
		provide visual feedback that the user has found the album they are looking for. 
		As this is the result of user actions, we believe we are protected under the DMCA 
		as a service provider, I would be more then happy to remove images for you, however 
		I would much prefer to make some sort of arrangement with you where Music by ZCD Media can 
		purchase a non-exclusive license to show such images.</p>
		
		<p>Music by ZCD Media is dedicated to making this site comply with all United States laws, 
		as such we respond quickly and positively to DMCA takedown requests. Unfortunately, we 
		cannot afford to have a registered DMCA takedown agent.</p>
		<p>All legal issues can be directed to: 
		<a href="mailto:support@zcd.me">support@zcd.me</a>.</p>
	</div>
</div>