<div id="browse_all_music">
	<div class="tab_header">
		<h2 class="tab_title">Contact:</h2>
	</div>
	<div class="tab_other_content_block" style="padding: 30px;">
		<p>All queries can be directed to: <a href="mailto:support@zcd.me">support@zcd.me</a></p>. 
		All emails will be answered.</p>
		
		<object type="application/x-shockwave-flash" data="https://clients4.google.com/voice/embed/webCallButton" width="230" height="85"><param name="movie" value="https://clients4.google.com/voice/embed/webCallButton" /><param name="wmode" value="transparent" /><param name="FlashVars" value="id=b4c7eaa6e1259506c07d10da817b7254cff73f76&style=0" /></object>

		<p>This site is copyright Mikehershey (Steven M. Hershey) 
		(or ZCD Media if I can ever afford the 
		LLC fees). As of now I have no address.</p>
	</div>
</div>