<div id="recently_viewed_playlist_holder" style="display: none">
	<div class="tab_header">
		<h2 class="tab_title">Play Queue:</h2>
	</div>
	<div id="recently_played_overlay" style="padding: 30px;">
		<div class="tab_other_content_block">
			<h3>This tab will display show songs that you played while searching or browsing, but you 
			haven't played any songs yet!</h3>
			<p>To get started click on Browse or Search link on the left sidebar, and look for music that you want to hear. 
			When you see something click the play button, and your music will start playing, and will be added to this list.
			When your done searching you can return to this, replay any songs you liked, or add them to your music library.</p>
		</div>
	</div>
	<table id="recently_played_playlist" class="tablesorter">
		<thead>
			<tr>
				<th style="width: 15px;"></th>
				<th>Name</th>
				<th>Artist</th>
				<th>Album</th>
				<th>Add to library</th>
				<th style="display: none;">Youtube ID</th>
			</tr>
		</thead>
		<tbody>
		</tbody> 
	</table>
</div>