<h1 style="width: 100%; text-align: center;color: #999999">Hello Internet Explorer user!</h1>
<h2 style="width: 100%; text-align: center;color: #999999">Unfortunately your web browser does not conform to web standards used by this site.</h2>
<h3 style="width: 100%; text-align: center;color: #999999">Please use one of these browsers (or any standards compliant browser):</h3>
<div style="width: 775px; margin-left: auto; margin-right: auto">
	<a href="http://www.google.com/chrome" style="border:0;"><img src="/images/IE/chrome-logo.png" style="border:0;"/></a>
	<a href="http://www.mozilla.org/en-US/firefox/new/" style="border:0;"><img src="/images/IE/firefox.png" style="border:0;"/></a>
	<a href="http://www.apple.com/safari/" style="border:0;"><img src="/images/IE/safari-logo.png" style="border:0;"/></a>
</div>